name: 部署到 GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 检出代码
        uses: actions/checkout@v4.2.2

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
